name: Release SPFx package

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  release:
    name: Release SPFx Package
    runs-on: ubuntu-latest
    steps:
      - name: Download Published Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          
      - name: Release Package
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: spfx-react-jest-testing.sppkg
          tag_name: ${{ inputs.tag_name }}
          name: Release v${{ inputs.tag_name }}