name: Test and release SPFx package

on:
  push:
    branches: [master]

  pull_request:

  workflow_dispatch:

concurrency:
  group: test-build-and-package-${{ github.ref }}

env:
  NODE_VERSION: '18.x'

jobs:
  test:
    name: Test SPFx with jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js v${{ env.NODE_VERSION }}, and NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: |
          npx jest --coverage --coverageReporters json-summary

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.26

  package:
    name: Package SPFx solution
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js v${{ env.NODE_VERSION }}, and NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Bundle solution
        run: gulp bundle --ship

      - name: Create sppkg package
        run: gulp package-solution --ship

      - name: publish build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sp-pkg
          path: sharepoint/solution/spfx-react-jest-testing.sppkg
          if-no-files-found: error

  release:
    name: Release SPFx solution
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: sp-pkg

      - name: Get Package Properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: config/package-solutions.json

      - name: Release SPFx Package
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: spfx-react-jest-testing.sppkg
          tag_name: ${{ steps.json_properties.solution.version }}
          name: Release v${{ steps.json_properties.solution.version }}
